[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = [
  'python3.11 -m ensurepip',
  'python3.11 -m pip install --upgrade pip',
  'python3.11 -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['python3.11 manage.py collectstatic --noinput']

[start]
cmd = 'python3.11 -m gunicorn audiopatch.wsgi --bind 0.0.0.0:$PORT'
